services:
  tsflow:
    build: .
    image: ghcr.io/rajsinghtech/tsflow:latest
    container_name: tsflow
    ports:
      - "8080:8080"
    environment:
      - TAILSCALE_OAUTH_CLIENT_ID=${TAILSCALE_OAUTH_CLIENT_ID}
      - TAILSCALE_OAUTH_CLIENT_SECRET=${TAILSCALE_OAUTH_CLIENT_SECRET}
      - TAILSCALE_OAUTH_SCOPES=${TAILSCALE_OAUTH_SCOPES}
      - TAILSCALE_API_KEY=${TAILSCALE_API_KEY}
      - TAILSCALE_TAILNET=${TAILSCALE_TAILNET}
      - TAILSCALE_API_URL=${TAILSCALE_API_URL}
      - PORT=8080
      - ENVIRONMENT=production
    env_file:
      - .env
    volumes:
      - tsflow_data:/app/data
    restart: unless-stopped

volumes:
  tsflow_data:
